# Generated by Django 3.1.3 on 2020-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatos_en_adopcion',
            name='foto',
            field=models.ImageField(default='/static/img/fotos_gats/g1.jpg', upload_to='fotos_gatos'),
        ),
    ]
